### ISSUE TITLE
Add ability to have this application start at Windows Logon

### ISSUE THREAD

**Issue by handruin** [handruin/spdif-ka#26]
New enhancement request identified by @mayerwin regarding a feature that will allow the user to have this application start at Windows Logon.  This idea and feature was discussed in the later part of issue   #14.  Tentative solution is to add a new checkbox under the settings that will create a shortcut under the StartUp folder on a user's system.

**Comment by mayerwin** [comment]
This feature has been implemented so this issue can be closed.
