### ISSUE TITLE
After S3 Sleep restart the tool

### ISSUE THREAD

**Issue by TimQSO** [handruin/spdif-ka#32]
When my PC goes into sleep and wakes up the tool doesn't work anymore, but it still says 'running'. I have top stop and start it manually to get it working again.

Not convenient on a HTPC.

Maybe a command line add on to restart the tool?

**Comment by vrubleg** [comment]
@GuiltyNL, as a workaround, you can try to use my program which solves the same task:
http://veg.by/en/projects/soundkeeper/
Maybe you will like it =)

**Comment by atrHusK** [comment]
soundkeeper does not detect my audio device at all, and since it is not configurable as far as I can see it is not a good replacement tool.
This sleep bug with spdif-ka is really annoying, I have build the project with the latest commits but unfortunately that did not solve anything. So this bug is still current.
Currently I work around it by added two scheduled jobs on the kernel power events for putting the computer to sleep and awaking, the actions are to kill the process and the start it again.

**Comment by mayerwin** [comment]
Did you try enabling the logs to see what was going on? Normally SPDIK-KA will detect any power or device change and restart the audio player systematically to avoid this kind of issue (I had it, this is why I implemented the event-based detection), so it is rather puzzling if it persists.

Here is a sample NLog.config file which you can use (to be placed within the same folder as the executable), it will produce a log file with verbose information:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">
  <targets>
    <target xsi:type="File" name="file"
            layout="${longdate}|${uppercase:${level}}|${logger}::${message}"
            fileName="SPDIFKA.log" deleteOldFileOnStartup="true" />
    <target xsi:type="Debugger" name="debugger" layout="${longdate:universalTime=true}|${level:uppercase=true}|${logger}->${message}"/>
  </targets>

  <rules>
    <!-- add your logging rules here -->
    <logger name="*" minlevel="Trace" writeTo="file,debugger" />
  </rules>
</nlog>
```

**Comment by mayerwin** [comment]
You may try with this pull request: https://github.com/handruin/spdif-ka/pull/33
I am not sure if I was running the code including this fix or not.
