### ISSUE TITLE
Application visible in task switcher

### ISSUE THREAD

**Issue by hzpc-joostk** [handruin/spdif-ka#4]
This discussion should shed some light on the idea of preventing the application from appearing in the windows task switcher (<kbd>Alt</kbd>+<kbd>Tab</kbd>). The application is hiding in the system tray, so why would it still appear in the task switcher?

**Comment by handruin** [comment]
Yep, I've reproduced the same issue and I'll look into hiding this from the alt+tab task switcher.  It should not show as a foreground app when minimized.  It's probably a property setting I missed; thanks for pointing this out.

**Comment by handruin** [comment]
Fixed this task switching issue in git commit fa81069595aaf265485dcf9aa586c0070eb25e7a.

**Comment by hzpc-joostk** [comment]
:+1:

**Comment by handruin** [comment]
Update, I fixed a new bug that I introduced in commit 6dd38ca9e9562627515adc9d6f326cc3d1dcffa8.
