### ISSUE TITLE
Suspected executable by F-Secure and Windows SmartScreen

### ISSUE THREAD

**Issue by hzpc-joostk** [handruin/spdif-ka#5]
There seems to be a problem with F-Secure (branded by my ISP). The DeepGuard detection marks the executable as suspected. Probably because its appearance on the web is very limited now. 
Here's a screenshot (in Dutch):
![knipsel](https://cloud.githubusercontent.com/assets/10130907/9499318/2296949c-4c1f-11e5-9933-b1727b5b9649.PNG)

The same happens with Windows SmartScreen.

I trusted the app, since I cannot find any problems in its source. :) And I think that this problem with fade away when more people start using the app. Or when Microsoft and F-Secure have scanned the executable themselves.

**Comment by hzpc-joostk** [comment]
Despite this event, the apps works flawlessly (on Windows 10 x64).

**Comment by handruin** [comment]
That's interesting to learn about; thanks for mentioning it.  I can run a scan on my executable when I get home this evening to see if I detect anything there.  If you are uncomfortable about using the compiled binary, the source is available under the github release (which was generated by github) and if you want I can help you setup Visual Studio 2013 community edition to build the executable yourself.

**Comment by hzpc-joostk** [comment]
No problem, @handruin. I see no need to compile it myself. It is just a quick, dirty and generic protection against unknown files. Probably based on a hash. :)

**Comment by handruin** [comment]
I added a new version and release.  I did a scan with ESET NOD32 and there were no issues detected.  If you still have an issue with this, please let me know.  I appreciate you help with making this app better.
