### ISSUE TITLE
On startup when state is set to minimized, app still shows in task switcher.

### ISSUE THREAD

**Issue by handruin** [handruin/spdif-ka#6]
Open spdif-ka and click on settings.
Select both check boxes.
Close spdif-ka
Launch spdif-ka.  It should now be running and minimized.
Using keyboard, press alt + tab
Notice it shows in the task switching UI when it should not.  If you restore the state of the GUI and then minimize it, this issue resolve itself.

**Comment by hzpc-joostk** [comment]
Hi @handruin, just letting you know that everything works fine! You've written a great app. You may want to close this issue. Cheers!

**Comment by vittau** [comment]
This issue happens to me as well (Windows 10), so it should not be closed. I don't have the time right now to check this though...
In any case, nice little utility, thank you!

**Comment by handruin** [comment]
Thanks for the feedback!  I checked and I'm also seeing the issue on Win 10 64-bit.  I'll work on fixing this and post the changes.

**Comment by handruin** [comment]
I know this is long overdue but I've finally addressed this issue.  Please let me know if you have any problems with this new release.  Thanks for your patience with this fix.

**Comment by vittau** [comment]
Thank you, it's fixed!
