### ISSUE TITLE
Win32 binary

### ISSUE THREAD

**Issue by chrhove** [handruin/spdif-ka#8]
Hi handruin,

Your app does exactly what I need on my Win10 box. 
I have two XP machines where I need the same functionality, but the binary won't run - It just generates an error: SPDIFKA.exe is not a valid Win32 application.
I guess the problem is that SPDIFKA is compiled for Win64. Would it be possible to talk you into compiling a Win32 binary?

**Comment by handruin** [comment]
Sure thing.  I can give it a try later tonight when I get home from work.  This may take a couple attempts with your help because I don't have any 32-bit Windows OSs to test with right now.

If you need it sooner and would like to try before I'm able to build it, all the source is here on Github and Visual Studio 2015 community edition is free (and exactly what I use to build this).

**Comment by chrhove** [comment]
I'll give Visual Studio a try :-)
Thanks

**Comment by handruin** [comment]
Let me know if you need any help getting VS2015 setup and building.  I downloaded [VS 2015 from Microsoft here](https://www.visualstudio.com/vs/community/).

I then used their built-in git utility to clone this repo and then opened the project in VS 2015.  I can't remember if VS ships with git but if not you may have to download that separately if you don't already have it.  

Even if you can't get git working, you can simply [download the latest release source zip file](https://github.com/handruin/spdif-ka/releases) and just expand it on your local system.  Point VS2015 to the *.sln file to open the project.

**Comment by handruin** [comment]
I've added a 32-bit binary to the release page that's available for download.  I've tried running it on my 64-bit system and it shows under task manager as a 32-bit application.  Let me know if this works for you.

**Comment by chrhove** [comment]
I've tested your 32-bit binary, but it won't run on the old XP machines - I built another version with the build options set to 32 bit and for .NET 4.0, which to my knowledge is the latest with XP support.
I had to disable the signing due to some certificate import failure.
The 32-bit build for .NET 4.0 seem to work as intended.
Thank you so much for your effort!

**Comment by handruin** [comment]
Ah, good call on the .NET version.  I forgot about the last version that XP supports.  I'm glad you were able to build it and get it working.  If you have any other issues please let me know.
